
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo install yarn...
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - yarn install
      - echo "Running tests... "
      - CI=true yarn test --coverage
  build:
    commands:
      - echo "Creating producion build ..."
      - yarn run build
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - '**/*'
  base-directory: build
  

