export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_IS_BUILDING_PATH = "SET_IS_BUILDING_PATH";
export const SET_NUM_MARKERS = "SET_NUM_MARKERS";
export const SET_MARKER_DETAILS_INFO = "SET_MARKER_DETAILS_INFO";
export const SET_ORDERED_MARKER_IDS = "SET_ORDERED_MARKER_IDS";
export const SET_PATHS = "SET_PATHS";

